export const LOADING_PHOTOS = "LOADING_PHOTOS";
export const LOADING_COMMENTS = "LOADING_COMMENTS";
export const LOAD_PHOTOS = "LOAD_PHOTOS";
export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const LOADING_AUTH = "LOADING_AUTH";
export const LOAD_AUTH = "LOAD_AUTH";
export const AUTH_FAILED = "AUTH_FAILED";

